
logging:
  level:
    org.springframework.r2dbc: DEBUG

server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/scholsm
    username: postgres
    password: postgres
    pool:
      enabled: true

